version: '3'

services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: babyfoot
    ports:
      - 5432:5432

  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - .:/home/node
    ports:
      - 8089:3100
    restart: always
